export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#07111f] pt-32 pb-24">
      <div className="max-w-4xl mx-auto px-6">
        <h1 className="text-4xl md:text-5xl font-heading font-bold text-white mb-8">
          Terms of <span className="text-[#d4af37]">Service</span>
        </h1>
        
        <div className="glass-card p-8 md:p-12 space-y-8 text-[#b8c2cc] font-sans">
          <section>
            <h2 className="text-2xl font-heading font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using LawGuide AI India ("Platform"), you agree to be bound by these Terms of Service. 
              If you do not agree to these terms, you must not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-bold text-white mb-4">2. Legal Disclaimer</h2>
            <div className="p-4 bg-[#ff4d4d]/10 border-l-4 border-[#ff4d4d] rounded-r-lg text-white/90">
              <strong>WARNING:</strong> LawGuide AI India is a technology platform, not a law firm. 
              The outputs generated by the AI engine do not constitute legal advice, and no attorney-client relationship is formed. 
              Users must consult registered Advocates for binding legal counsel.
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-bold text-white mb-4">3. Prohibited Activities</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>Reverse engineering or scraping the underlying `legalEngine.ts` logic.</li>
              <li>Uploading classified, top-secret, or highly sensitive third-party PII without consent.</li>
              <li>Attempting to bypass API rate limits or security headers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-bold text-white mb-4">4. Limitation of Liability</h2>
            <p>
              While the platform utilizes deterministic logic engines to minimize AI hallucinations, legal statutes are subject to interpretation and frequent amendments. 
              The platform operator assumes no liability for any direct or indirect damages resulting from actions taken based on this tool.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
